repos:
  - repo: local
    hooks:
      - id: black
        name: run black
        entry: black
        language: python
        files: ^(funda_scraper|tests)/.*\.py$
        args: ["--line-length=120"]

      - id: isort
        name: run isort
        entry: isort
        language: python
        files: ^(funda_scraper|tests)/.*\.py$
        language_version: python3