header:
  user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36"
base_url: https://www.funda.nl/en
keep_cols:
  sold_data:
    - date_sold
    - ym_sold
    - year_sold
  #    - term_days
  selling_data:
    - url
    - house_id
    - city
    - house_type
    - building_type
    - price
    - price_m2
    - room
    - bedroom
    - bathroom
    - living_area
    - energy_label
    - zip
    - address
    - year_built
    - house_age
    # - date_list
    # - ym_list
    # - year_list
    - descrip
    - photo
css_selector:
  url: none
  price: "section.mt-6 > div:nth-child(2) > dl:nth-child(2) > dd:nth-child(2) > span:nth-child(1)"
  address: ".object-header__title"
  descrip: ".object-description-body"
  listed_since: "section.mt-6 > div:nth-child(2) > dl:nth-child(2) > dd:nth-child(6) > span:nth-child(1)"
  zip_code: "span.text-neutral-40:nth-child(2)"
  size: ".object-kenmerken-list:nth-child(8) .fd-align-items-center:nth-child(5) span"
  year: ".fd-align-items-center~ .fd-align-items-center .fd-m-right-xs"
  year_of_construction: ".mt-6.md\\:mt-7 > div:nth-of-type(2) > dl > dd:nth-of-type(3) span"
  living_area: "section.mt-6 > div:nth-child(4) > dl:nth-child(2) > dd:nth-child(4)"
  kind_of_house: ".mt-6.md\\:mt-7 > div:nth-of-type(2) > dl > dd:nth-of-type(1) span"
  building_type: "section.mt-6 > div:nth-child(3) > dl:nth-child(2) > dd:nth-child(4) > span:nth-child(1)"
  num_of_rooms: ".mt-6.md\\:mt-7 > div:nth-of-type(4) > dl > dd:nth-of-type(1) span"
  num_of_bathrooms: ".mt-6.md\\:mt-7 > div:nth-of-type(4) > dl > dd:nth-of-type(2) span"
  layout: ".object-kenmerken-list:nth-child(11)"
  energy_label: ".gap-6 > div:nth-child(1)"
  insulation: ".mt-6.md\\:mt-7 > div:nth-of-type(5) > dl > dd:nth-of-type(2) span"
  heating: ".mt-6.md\\:mt-7 > div:nth-of-type(5) > dl > dd:nth-of-type(3) span"
  ownership: ".mt-6.md\\:mt-7 > div:nth-of-type(6) > dl > dd:nth-of-type(2) span"
  exteriors: ".object-kenmerken-list:nth-child(19)"
  parking: ".mt-6.md\\:mt-7 > div:nth-of-type(5) > dl > dd:nth-of-type(1) span"
  neighborhood_name: ".object-header__container > a"
  date_list: "dd:nth-child(2)"
  date_sold: "dd:nth-child(4)"
  term: "dd:nth-child(6)"
  price_sold: ".object-header__price--historic"
  last_ask_price: "section.mt-6 > div:nth-child(2) > dl:nth-child(2) > dd:nth-child(2) > span:nth-child(1)"
  last_ask_price_m2: "section.mt-6 > div:nth-child(2) > dl:nth-child(2) > dd:nth-child(4) > span:nth-child(1)"
  photo: ".media-viewer-overview__section-list-item--photo img[data-lazy]"
